version: '3'

services:
  idrac1:
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5801:5800
      - 5901:5900
    environment:
      - CMC_HOST=10.0.0.1
      - CMC_USER=admin
      - CMC_PASSWORD=example
      - CHASSIS_ID=1
    volumes:
      - /home/petterroea/Downloads:/vmedia